trigger:
- main  # or your target branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

# ✅ Use Java 17
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitecture: 'x64'
    jdkSourceOption: 'PreInstalled'

# ✅ Confirm Java version
- script: |
    echo "JAVA_HOME=$JAVA_HOME"
    java -version
    mvn -version
  displayName: 'Verify Java & Maven version'

# ✅ Run Maven build
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'  # Adjust path if needed
    goals: 'clean install'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
